/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Auth: () => import('#controllers/AuthController'),
  Cliente: () => import('#controllers/ClienteController'),
  Conta: () => import('#controllers/ContaController'),
  Extrato: () => import('#controllers/ExtratoController'),
  Investimento: () => import('#controllers/InvestimentoController'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Transacaos: () => import('#controllers/TransacaosController'),
}
